source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'pg'
gem 'paperclip'
gem 'ankaa-statistic', git: 'git@bitbucket.org:myxrome/ankaa-statistic.git'
gem 'ankaa-content', git: 'git@bitbucket.org:myxrome/ankaa-content.git'
gem 'active_model_serializers'
gem 'figaro'
gem 'unicorn'